# Setup {.unnumbered}

In den Übungen werden wir die Programmiersprache Python verwenden, um
die in der Vorlesung behandelten Themen zu erklären und an realen Daten
zu üben. Die Übungen werden in Form von Jupyter Notebooks bereitgestellt,
die Sie in Ihrer eigenen Umgebung ausführen können.

Deswegen ist es notwendig, zuerst eine Arbeitsumgebung einzurichten.

## Git

Die Übungen werden in einem Git-Repository auf GitHub bereitgestellt. Git ist ein Versionskontrollsystem, das die Änderungen an Dateien verfolgt und es ermöglicht, verschiedene Versionen von Dateien zu speichern. GitHub ist eine Plattform, die auf Git basiert und es ermöglicht, Git-Repositories zu hosten und zu teilen.

Wir werden Git verwenden, um die Übungen herunterzuladen und um Ihre Lösungen hochzuladen.

Installieren Sie Git von [https://git-scm.com/downloads](https://git-scm.com/downloads). Wählen Sie die Version, die zu Ihrem Betriebssystem passt und folgen Sie den Anweisungen.
Lassen Sie die Standardeinstellungen unverändert, es sei denn, Sie wissen ganz genau, was Sie tun.

## GitHub Account

Für die Übungen brauchen Sie ein GitHub.com Konto:

- Erstellen Sie ein Konto auf [https://github.com/signup](https://github.com/signup).
- Bei der Registrierung wählen Sie ein Passwort, das Sie nirgendwo anders verwenden. Am Ende des Semesters können Sie Ihr Passwort ändern.
- Empfehlung: Aktivieren Sie die [Zwei-Faktor-Authentifizierung (2FA)](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-github-mobile) in den Einstellungen Ihres GitHub-Kontos.
- Empfehlung: Beantragen Sie die [Studentenvorteile](https://education.github.com/discount_requests/application), um kostenlosen Zugang zu GitHub Copilot zu erhalten, einem KI-gestützten Code-Completion- und Chat-Tool.


## Visual Studio Code

Visual Studio Code (VSC) ist ein Open-Source-Code-Editor, den wir für die Arbeit mit Python benutzen werden.

Installieren Sie Visual Studio Code von [https://code.visualstudio.com/](https://code.visualstudio.com/). Wählen Sie die Version, die zu Ihrem Betriebssystem passt und folgen Sie den Anweisungen.

## Kursrepository klonen

Öffnen Sie VSC und drücken Sie `Ctrl+Shift+P`. Suchen Sie nach "Git: Clone" und drücken Sie Enter. Geben Sie die URL des Kursrepositories ein:

```plaintext
http://github.com/febse/econ2024-de.git
```

Wählen Sie einen Ordner auf Ihrem Computer, in dem Sie das Repository speichern möchten. VSC wird das Repository herunterladen und fragen, ob Sie es öffnen möchten. Klicken Sie auf "Open".

Warten Sie einen Moment, bis VSC das Repository geöffnet hat. Sie sollten eine Ordnerstruktur sehen, die den Inhalt des Repositories darstellt.
VSC wird Sie fragen, ob Sie die empfohlenen Erweiterungen installieren möchten. Klicken Sie auf "Install All".

Am Ende sollten Sie die folgenden Erweiterungen installiert haben:

- ms-python.autopep8
- ms-python.python
- ms-python.debugpy
- ms-vscode-remote.remote-containers
- ms-toolsai.jupyter
- github.codespaces
- github.copilot

Drucken Sie `Ctrl+Shift+X`. Dieses wird die Erweiterungsansicht öffnen. Überprüfen Sie ob alle Erweiterungen installiert sind. Falls nicht, kopieren Sie die Kennzeichen (z.B. `ms-python.autopep8`) der fehlenden Erweiterungen von der Liste (oben), finden Sie die Erweiterungen in der Erweiterungsansicht und installieren Sie sie manuell.


## Python

Python ist zurzeit eine der meistbenutzten Programmiersprachen in der Welt. Es ist einfach zu lernen und hat eine große Community, die viele Bibliotheken und Frameworks entwickelt hat. In der Welt der Datenwissenschaft werden meistens Python und R benutzt. In den letzten Jahren stieg die Popularität von Python.

### Codespaces (empfohlen)

Um die Konfiguration zu vereinfachen, können Sie Codespaces benutzen. In den ersten Übungen werden wir eine Anleitung zeigen, wie Sie Codespaces benutzen können.


### Miniconda

Es gibt viele Möglichkeiten, wie Sie Python local auf Ihrem Rechner installieren können. Hier zeigen wir die Installation mit Miniconda. Conda ist ein Paketmanager, der es ermöglicht, Python-Umgebungen zu verwalten. Eine Python-Umgebung ist eine isolierte Instanz von Python, die es ermöglicht, verschiedene Versionen von Python und verschiedenen Bibliotheken zu verwenden, ohne dass sie sich gegenseitig beeinflussen. Das ist vor allem dann nützlich, wenn Sie an verschiedenen Projekten arbeiten, die unterschiedliche Anforderungen an Python und Bibliotheken haben.


- Laden Sie das Miniconda Installationspaket von [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html) für Ihr Betriebssystem.
- Starten Sie das Packet und folgen Sie den Anweisungen. Lassen Sie die Standardeinstellungen unverändert, es sei denn, Sie wissen was Sie tun.
- Installieren Sie Conda in einem Ordner ohne Leerzeichen und nur mit ASCII Zeichen im Pfad (d.h. keine Kyrillischen Zeichen, keine Umlaute, etc.), z.B. `C:\Miniconda3` oder `C:\Users\boyko\Miniconda3`.

- Nachdem Miniconda installiert ist, öffnen Sie VSC. Drücken Sie `Ctrl+Shift+P` und starten Sie zu schreiben: "Python: Create environment". Wenn die Option in dem Dropdown-Menü erscheint, wählen Sie sie und drucken Sie Enter.
- Wählen Sie "Conda".
- Wählen Sie die Python-3.11 Version.
- Dieses wird einen Order namens `.conda` erstellen.
- Falls Sie diese Schritte in dem Order des Kursrepositories gemacht haben, werden dann automatisch die notwendingen Bibliotheken installiert.

## Pycharm (optional)

Statt VSC können Sie auch PyCharm oder DataSpell benutzen. PyCharm ist eine integrierte Entwicklungsumgebung (IDE) für Python, die von JetBrains entwickelt wurde. PyCharm ist eine der beliebtesten Python-IDEs und bietet viele Funktionen, die die Entwicklung von Python-Programmen erleichtern. Falls Sie mit PyCharm oder DataSpell experimentieren möchten, bieten wir für die Übungen kostenfreie Lizenzen an.

- Registrieren Sie sich auf [https://account.jetbrains.com/signup](https://account.jetbrains.com/signup) mit Ihrer Universitäts-E-Mail-Adresse (muss auf `feb.uni-sofia.bg` oder `feba.uni-sofia.bg` enden).
- Laden Sie Pycharm von [https://www.jetbrains.com/pycharm/download/](https://www.jetbrains.com/pycharm/download/) herunter und installieren Sie es.
- Beim Aktivierungsdialog wählen Sie "Licence Server" und geben Sie `https://febs.fls.jetbrains.com/` ein.
